[connections.postgresql]
dialect = "postgresql"
host = "db.hcccwrjngbsbftapzums.supabase.co"
port = 5432
database = "postgres"
username = "postgres"
password = "multi-techGOAT"
# For supabase, sslmode might be required. E.g.
# query = {"sslmode": "require"}
